spring.application.name=UrlShortenerApplication

spring.datasource.url=jdbc:mysql://localhost:3306/urlshort?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=your_actual_password
spring.jpa.hibernate.ddl-auto=update
server.forward-headers-stmvn clean packagerategy=native